#!/usr/bin/env bash
set -e
shopt -s nullglob

njobs=$(nproc)

task=$1

export PARALLEL=--no-notice

LISTS=(
	hclim_historical+ssp126
	hclim_historical+ssp370
	gcm_historical+ssp126
	gcm_historical+ssp370
)

LISTS_ENS=(
	hclim_ens_historical+ssp126
	hclim_ens_historical+ssp370
	gcm_ens_historical+ssp126
	gcm_ens_historical+ssp370
)

LISTS_INDICES=(
	hclim_historical+ssp370_day
)

LISTS_MAP_MEAN=(
	hclim_historical+ssp126
)

LISTS_MAP_DIFF=(
	hclim_historical+ssp370
)

LISTS_HEATMAP_MEAN=(
	hclim_historical+ssp126
)

LISTS_HEATMAP_DIFF=(
	hclim_historical+ssp370
)

SUBTYPES=(
	period_season
	period_season_region
)

INDICES=(
	sd
)

tmp=$(mktemp)
tmp_final=$(mktemp)
trap 'rm -- "$tmp" "$tmp_final"' EXIT

cmd () {
	echo $* >> "$tmp"
}

run () {
	# cat "$tmp"
	parallel -tuj "$njobs" < "$tmp"
	echo > "$tmp"
}

calc_stats () {
	local input=$1
	local list=$2
	local subtype=$3
	local out=$4
	mkdir -p "$out"
	for source in $(cat "sources/list/${list}"); do
		cmd bin/calc_stats "$subtype" "$input/$source"_mon "$source" "$out"
	done
}

convert_png () {
	local dir=$1
	out=$dir/png
	mkdir -p "$out"
	for file in "$dir/"*.pdf; do
		cmd \
			convert \
			-density 600 \
			"$file" \
			"$out/$(basename "${file%.pdf}").png"
	done
}

case "$task" in

"")
	cat <<EOF
Usage: run TASK

Tasks:

  source_links          Create source symlinks in the input directory.
  remap_landmask        Remap land mask to a 1x1 degree grid for GCM calculations.
  remap_obs             Remap observatiosn to a 1x1 degree grid for GCM calculations.
  calc_ensembles        Calculate model ensembles.
  calc_stats            Calculate statistics (dep: source_links, remap_landmask, remap_obs, ensemble).
  calc_indices          Calculate climate indices.
  calc_model_ranking    Calculate model ranking (dep: calc_stats).
  plot_map_mean         Plot maps for means (dep: calc_stats).
  plot_map_diff         Plot maps for differences between time periods (dep: calc_stats).
  plot_map_trend        Plot maps for linear trends (dep: calc_stats).
  plot_heatmap_mean     Plot heatmaps for means (dep: calc_stats).
  plot_heatmap_diff     Plot heatmaps for differences between time periods (dep: calc_stats).
  plot_heatmap_trend    Plot heatmaps for trends (dep: calc_stats).
  plot_boxplot          Plot boxplots with statistics (dep: calc_stats).
  plot_gcm_rcm_scatter  Plot GCM-RCM scatter plot for temperature and precipitation (dep: calc_stats).
  plot_model_ranking    Plot model ranking (dep: model_ranking).
  plot_timeseries       Plot time series (dep: calc_stats).
  plot_annual_cycle     Plot annual cycle (dep: calc_stats).
  plot_gcm_rcm_tas      Plot GCM. vs RCM. temperature change.
EOF
	;;

source_links)
	out=input/sources
	mkdir -p "$out"
	while read -r line; do
		items=($line)
		name=${items[0]}
		out1=$out/$name
		mkdir -p "$out1"
		for path in ${items[@]:1}; do
			for file in "$path"/*.nc; do
				if [ -e "$file" ]; then
					cmd ln -fs "$file" -t "$out1/"
				fi
			done
		done
	done < "sources/paths"
	;;

remap_landmask)
	out=data/landmask
	mkdir -p "$out"
	cmd cdo \
		remapbil,r360x180 \
		input/landmask/sftlf_EUR-12_ERA5_evaluation_r1i1p1f1_HCLIMcom-SMHI_HCLIM43-ALADIN_v1-r1_fx.nc \
		"$out/sftlf_EUR-12_ERA5_evaluation_r1i1p1f1_HCLIMcom-SMHI_HCLIM43-ALADIN_v1-r1_fx_1x1deg.nc"
	;;

remap_obs)
	for obs in $(cat sources/list/obs); do
		out=data/1deg/$obs
		mkdir -p "$out"
		for file in "input/sources/$obs"/*; do
			cmd cdo \
				remapbil,r360x180 \
				"$file" \
				"$out/$(basename "$file")"
		done
	done
	;;

calc_ensembles)
	mkdir -p data/ensembles
	for list in "${LISTS_ENS[@]}"; do
		cmd bin/calc_ensemble \
			input/sources $(cat "sources/list/$list") \
			data/ensembles
	done
	run
	for file in data/ensembles/*; do
		cmd ln -sf "../../data/ensembles/$(basename "$file")" -t input/sources
	done
	;;

calc_stats)
	for list in "${LISTS[@]}"; do
		for subtype in "${SUBTYPES[@]}"; do
			calc_stats input/sources \
				"$list" \
				"$subtype" \
				"data/stats/$list/$subtype"
		done
	done
	for subtype in "${SUBTYPES[@]}"; do
		calc_stats input/sources obs "$subtype" "data/stats/obs/$subtype"
		calc_stats data/1deg obs "$subtype" "data/stats/obs_1deg/$subtype"
	done
	run
	for list in "${LISTS[@]}"; do
		for subtype in "${SUBTYPES[@]}"; do
			dir=$([[ "$list" == gcm_* ]] && echo obs_1deg || echo obs)
			parallel ln -sf "../../$dir/$subtype/{/}" "data/stats/$list/$subtype" \
				::: "data/stats/$dir/$subtype"/*
		done
	done
	for list in "${LISTS[@]}"; do
		for subtype in "${SUBTYPES[@]}"; do
			cmd bin/index "data/stats/$list/$subtype"
		done
	done
	;;

calc_indices)
	out=data/indices/tmp
	mkdir -p "$out"
	for list in "${LISTS_INDICES[@]}"; do
		for source in $(cat "sources/list/$list"); do
			for index in "${INDICES[@]}"; do
				for file in "input/sources/$source"/*; do
					echo cmd bin/climix -x "$index" "$file" "$out"
				done
			done
		done
	done
	run
	for file in "$out"/*; do
		echo mv "$file" data/indices/$(bin/get_source_name "$out/$file")
	done
	;;

plot_map_mean)
	for list in "${LISTS_MAP_MEAN[@]}"; do
		out=plot/map_mean/$list
		mkdir -p "$out"
		cmd bin/plot_map \
			mean \
			"data/stats/$list/period_season" \
			$(cat sources/list/{obs,"$list"}) \
			"$out"
	done
	;;

plot_map_trend)
	for list in "${LISTS_MAP_MEAN[@]}"; do
		out=plot/map_trend/$list
		mkdir -p "$out"
		cmd bin/plot_map \
			trend \
			"data/stats/$list/period_season" \
			$(cat sources/list/{obs,"${list}"}) \
			"$out"
	done
	;;

plot_map_diff)
	for list in "${LISTS_MAP_DIFF[@]}"; do
		out=plot/map_diff/$list
		mkdir -p "$out"
		cmd bin/plot_map \
			diff \
			"data/stats/$list/period_season" \
			$(cat "sources/list/$list") \
			"$out"
	done
	;;

plot_heatmap_mean)
	out=plot/heatmap_mean/$list
	mkdir -p "$out"
	for list in "${LISTS_HEATMAP_MEAN}"; do
		cmd bin/plot_heatmap \
			mean \
			"data/stats/$list/period_season_region" \
			$(cat sources/list/{obs,"$list"}) \
			"$out"
	done
	;;

plot_heatmap_trend)
	out=plot/heatmap_trend/$list
	mkdir -p "$out"
	for list in "${LISTS_HEATMAP_TREND}"; do
		cmd bin/plot_heatmap \
			trend \
			"data/stats/$list/period_season_region" \
			$(cat sources/list/{obs,"$list"}) \
			"$out"
	done
	;;

plot_heatmap_diff)
	out=plot/heatmap_diff/$list
	mkdir -p "$out"
	for list in "${LISTS_HEATMAP_DIFF}"; do
		cmd bin/plot_heatmap \
			diff \
			"data/stats/$list/period_season_region" \
			$(cat "sources/list/$list") \
			"$out"
	done
	;;

plot_boxplot)
	out=plot/boxplot
	mkdir -p "$out"
	cmd bin/plot_boxplot \
		data/stats/hclim_historical+ssp126/period_season_region \
		$(cat sources/list/{obs,hclim_historical+ssp126}) \
		1991 2020 \
		"$out"
	out=plot/boxplot_relative
	mkdir -p "$out"
	cmd bin/plot_boxplot_relative \
		data/stats/hclim_historical+ssp126/period_season_region \
		$(cat sources/list/{obs,hclim_historical+ssp126}) \
		1991 2020 \
		"$out"
	;;

plot_gcm_rcm_scatter)
	out=plot
	mkdir -p "$out"
	cmd bin/plot_gcm_rcm_scatter \
		data/stats/{gcm_historical+ssp126,hclim_historical+ssp126}/period_season_region \
		$(cat sources/list/hclim_historical+ssp126) \
		1991 2020 \
		"$out/gcm_rcm_scatter.pdf"
	;;

calc_model_ranking)
	out=data
	mkdir -p "$out"
	cmd bin/calc_model_ranking \
		data/stats/hclim_historical+ssp126/period_season_region \
		$(cat sources/list/hclim_historical+ssp126_ranking) \
		1991 2020 \
		"$out/model_ranking.nc"
	;;

plot_model_ranking)
	out=plot
	mkdir -p "$out"
	cmd bin/plot_model_ranking data/model_ranking.nc "$out/model_ranking.pdf"
	;;

plot_timeseries)
	out=plot/timeseries
	mkdir -p "$out"
	cmd bin/plot_timeseries \
		data/stats/hclim_historical+ssp370/period_season_region \
		$(cat sources/list/hclim_historical+ssp370) \
		1991 2020 \
		1991 2100 \
		2071 2100 \
		"$out/hclim_historical+ssp370.pdf"
	;;

plot_annual_cycle)
	out=plot
	mkdir -p "$out"
	cmd bin/plot_annual_cycle \
		data/stats/hclim_historical+ssp370/period_season_region \
		$(cat sources/list/hclim_historical+ssp370) \
		1991 2020 \
		2071 2100 \
		"$out/annual_cycle.pdf"
	;;

plot_gcm_rcm_tas)
	out=plot
	mkdir -p "$out"
	cmd bin/plot_gcm_rcm_tas \
		data/stats/gcm_historical+ssp370/period_season_region \
		data/stats/hclim_historical+ssp370/period_season_region \
		$(cat sources/list/hclim_ens_historical+ssp370) \
		1991 2020 \
		2071 2100 \
		"$out/gcm_rcm_tas.pdf"
	;;

*)
	echo "$0: unknown task \"$task\"" >&2
	exit 1

esac

run
